account_button = '//div[text()="Account"]'
ls_button= '//button[text()="Login/Signup Now"]'
enter_no='//input[@name="mobileInput"]'
submit_button='//*[@id="portal-root"]//button[text()="Submit"]'
Verify_button='//button[text()="Verify OTP"]'
search_box='//input[@placeholder="Search for products, styles, brands"]'
item_clicked='//span[text()="Puma bmw shoes"]'
item= '//*[@id="app"]//div/a[@href="/puma-bmw-mms-electron-e-mens-white-sneakers/p/6762486"]'
size_click='//button[text()="UK 6"]'
add_button='//button[text()="Add to Bag"]'
cart='//div[text()="Cart"]'
checkout='//button[text()="Proceed to Buy"]'
pinc='//label[text()="Pincode*"]'
adl1='//label[text()="Address line 1*"]'
adl2='//label[text()="Address line 2*"]'
nm='//label[text()="Full Name*"]'
